### ISSUE TITLE
Page owner in Create Compendia

### ISSUE THREAD

**Issue by jaseiler** [researchcompendia/researchcompendia#100]
Users really shouldn't see a list of all users on the form.  It would be much better to just have it auto-fill to the logged in user name, and a check to see if the entered value is an existing user if they change it.

This will be important if we get more users.

**Comment by codersquid** [comment]
Maybe we shouldn't allow people to transfer ownership during creation. This might solve some problems
- prevents a user from transferring ownership to the wrong user
- prevents the wrong owned compendia appearing on someone's profile

If we prevent users from being able to control ownership, then it would be a good idea to provide a mechanism for handing off ownership -- we could examin how other sites handle this, e.g. github with repo ownership. When someone transfer ownership to a repository, it happens in stages. They hand it off and no longer have control, but the transfer isn't complete until the other user accepts.

**Comment by codersquid** [comment]
code is checked in and deployed to labs.
