### ISSUE TITLE
Login page for create compendia

### ISSUE THREAD

**Issue by jaseiler** [researchcompendia/researchcompendia#102]
When people click "Create Compendia" It takes them to the login page. 
The Register option needs to show up within that page, not just in the header.

"Not already a member?  [Sign up](/accounts/signup)!"

**Comment by codersquid** [comment]
Once the travis build passes, this will be ready for review.

**Comment by codersquid** [comment]
I ran it locally and also have deployed it to http://labs.researchcompendia.org/accounts/login/

**Comment by jaseiler** [comment]
Looks good!
