### ISSUE TITLE
authors and contributors on compendia details page

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#112]
We should have a details page that displays well-formed information about authors and coders rather than plain text. Plain text is our fallback for the first release, and we will want this soon.

I've got a JSONField for authorship in the Article model, and a m2m contributors field. The JSONField can have an arbitrary map of metadata about authors/coders which would allow us storing information about authorship that includes non users -- that is clunky but depending on schedule I wanted to be able to do that without going through the trouble of setting up a cache/non-rel type of thing. It's like a baby non-rel.

The UI doesn't need to concern itself about where the data comes from, and we should establish an interface so that the work on the UI can proceed regardless of what backend delivers the data to it.

So, maybe we'll have more than one issue, or maybe just this one, but regardless
- make a minimum viable interface def -- assume json, and don't overthink things for now. we can be flexible and change stuff
- working from that, do UI work
- work will need to happen for populating the dictionary -- we could have it happen at compendia creation/update. if we want a non-rel store hanging around in a cache rather than a JSONField, work will need to happen to handle the cache. etc.

**Comment by jaseiler** [comment]
also (don't know if here is appropriate) authors (or up to 6-8 authors) should appear on the browse views for papers.

**Comment by codersquid** [comment]
That makes sense. We could have a behavior similar to the truncation for the abstract, or we could something else. being able4 to click on author names in the browse card could be nice rather than just seeing text.

**Comment by codersquid** [comment]
I have the first version of this, very stupid, all it does is take whatever text is in authors_text, truncates to 100 chars and shows it on the card. It's deployed to labs now and is in 7348dfd0ee740b0bd1c8e7ba5d8c1a455ea9359c

**Comment by jaseiler** [comment]
Looks great!
