### ISSUE TITLE
create resources template

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#135]
Have a template to contain links to papers, slides, presentations, etc.

**Comment by codersquid** [comment]
I've added https://github.com/researchcompendia/researchcompendia/blob/resourcespage/companionpages/templates/resources.html and you can edit the content there in that branch directly via the github UI or on your filesystem. If you don't have a dev environment set up to view changes locally, I could walk you through it, or I could just deploy this for you.

**Comment by codersquid** [comment]
You can see how it looks here http://labs.researchcompendia.org/resources/ with the unrelated text as example.

**Comment by codersquid** [comment]
this is not deployed at the moment. I deployed 1.0.1-b1 and will get this back up after a bit.

**Comment by codersquid** [comment]
I merged this in to develop and deployed it to staging, so you can see the example and the navbar change.

http://labs.researchcompendia.org/resources/

**Comment by jaseiler** [comment]
I still see the same problem with the navbar.

**Comment by codersquid** [comment]
Yes. that issue is still open and not being worked on.

**Comment by codersquid** [comment]
I'm going to change this to a flatpage for now so that we have something up and easily editable in the admin interface.

**Comment by codersquid** [comment]
This http://labs.researchcompendia.org/resources/ is now a flatpage and can be edited from the flatpages admin. Once we are happy with the content, I'll add a nav link and push it to production.
