### ISSUE TITLE
add field for editor notes that is public

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#143]

**Comment by jaseiler** [comment]
Just to be clear, I mean the box will only show up in the admin editor for compendia, and what goes in there will be publicly visible on the final page.

**Comment by codersquid** [comment]
I'm going to do the south migration for this today.

**Comment by codersquid** [comment]
I lied. I'm going to rethink this. At first I was thinking just to add a new field. But then I started thinking we could have a new table like ArticleNotes and then use permissions to allow people in a group to be able to create notes that will render on the compendia page. Before I overcomplicate things, I would like to know more use cases. What would like to have in a note on a compendia page? Would you like the ability to attach more than one note? Would you like to be able to have any user in a group that we define to be able to edit/update/add a note(s)?

**Comment by codersquid** [comment]
added admin note in this commit that is in labs right now https://github.com/researchcompendia/researchcompendia/commit/1d22f2562a7805bbe99d43e47f6b814e769d4770#diff-399dc57903c8eb82d4194a474fd99f2fR108
