### ISSUE TITLE
doi auto-fill for site creation

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#43]
I'll merge in Jenn's changes after doing some additional clean up.

**Comment by codersquid** [comment]
Jenn was using urllib and some other libraries, I'm going to go ahead and use requests and probably xmltodict.

It works something like this.

```
import requests
import xmltodict

    r = requests.get('http://doi.crossref.org/openurl/', params={
            'pid': 'example@example.com',
            'noredirect': True,
            'id': 'doi:10.1006/jmbi.2000.4282',
            'format': 'unixref',
    })
    d = xmltodict.parse(r.text)
```

```
```

**Comment by codersquid** [comment]
I have an api set up and partially done so that a client (including our frontend) could request information from a doi ref service to get information suitable for populating our models. This is partly done, but you can review the code that I've checked in so far.

I've deployed the changes to rose-tyler-alpha if you want to try them out. hit the link this way:

http://rose-tyler-alpha.herokuapp.com/api/v1/dois?doi=10.1109/UKSIM.2011.38

passing a doi string (without the "doi:" part) to get a message that is very basic for now. It will be a json message with "status", "msg", and optionally "xml".

**Comment by codersquid** [comment]
Next for this will be to finish up the parsing bit to map info from the query to our Article and Collaborator models. nevermind the xmltodict comment, I'll use beautifulsoup4. It's been great for when I've needed to parse html, and it can do xml as well.

```
from bs4 import BeautifulSoup

soup = BeautifulSoup(open('sample.txt'), 'lxml')
# want a doi_record if it exists? just try to access it:
result = soup.doi_record
```

**Comment by codersquid** [comment]
Stopping work on this for half today to pick up documentation task.

**Comment by codersquid** [comment]
Changes on this feature branch are on rose-tyler-alpha right now, with this minimalistic test page http://rose-tyler-alpha.herokuapp.com/compendia/doi/

**Comment by codersquid** [comment]
this code lives here for now https://github.com/researchcompendia/tyler/blob/develop/companionpages/lib/crossref.py

**Comment by codersquid** [comment]
This slipped from today's release. If you want to see where I left off, here is hte naive jquery code on the create page, https://github.com/researchcompendia/tyler/blob/develop/companionpages/templates/compendia/create.html#L40  before I swapped out of doing this task.

the approach I was taking was to have a form for doi lookup that would hit our api to get the crossref scrape cleaned up for our model. the javascript start was the part to hit the api, and then I'd write a function to modify the dom accordingly. since we don't have a lot of scrapers for papers yet, modifying to get a paper abstract would be done in another step, but similarly. The crossref api provides links to the paper that we can follow (or we can see what the user tells us directly)

**Comment by jaseiler** [comment]
Should we remove the "fetch doi" button for now, considering that it currently does nothing?

**Comment by codersquid** [comment]
Doh. Yes. I can't believe I forgot to do that.

**Comment by codersquid** [comment]
I removed it, and deployed the change to http://preprod-researchcompendia.herokuapp.com/ let me know if that looks fine and I'll deploy it to production.

**Comment by codersquid** [comment]
This is ready to review, I have it merged with the news branch at  http://preprod-compendia.herokuapp.com/

**Comment by jaseiler** [comment]
looks good!  ready to push!
