### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#50]
- [x] link to associated compendia
- [ ] link out to user provided sites (ORCID?)

**Comment by victoriastodden** [comment]
The account creation page should definitely have a way for a user to enter
their ORCID ID. Maybe in a field below "email address," could be "ORCID ID
(highly recommended)"

People should be able to add it later, but i think we will have the most
success with this by getting authors to enter it on the way in.

Thanks,
Victoria

**Comment by codersquid** [comment]
Status update: replaced libraries I was using with django-allauth, which provides local and social login/registration and some nicer features than before. django-allauth is a good library to use since it's in more active development than the others.

**Comment by codersquid** [comment]
Opened #63 to track things like linking ORCID (and other sites).
