### ISSUE TITLE
specifying licensing for content

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#53]
I'm breaking this out from a task for #4 because I think it calls for its own issue.

At a minimum, we should allow people to pick a license for their code and their content. Beyond that, we should actually give them a way to understand licensing and the consequences of the license they pick. The CC has a good site for guiding people, and I've also found http://choosealicense.com/ which guides people through selecting a code license and directs them to CC if they need to license content.

I want to figure out a good way for someone to experience the process of creating a compendia and choosing license -- and would like to have a seamless way for them to go through a site like the CC license picker and things like that.

I'll go for the minimum for the first iteration. Having a seamless experience is more complicated, but perhaps it will be obvious enough to include in the first iteration. If not, we can plan for it in another issue. I'll leave this as one issue for now, and perhaps break it out if it seems productive to do so.

**Comment by victoriastodden** [comment]
They don't get to pick the license. They can request an exception to our
default licensing however.

Victoria

**Comment by codersquid** [comment]
I'll implement what we need. Let's establish that, and then figure out a user experience for someone who wants to request an exception. Here are my thoughts and ideas.

Ideas for defaults
- CC-BY or maybe CC0 for content
- MIT for code.
  - people should be able to share code with licenses that we show from http://opensource.org/licenses
- I am not sure how to license data, what is used for data?

for exceptions
- have a drop-down of pre-approved alternatives.
- licenses not on the pre-approved list force a compendium in to "draft" mode, and we'll have a queue for moderation where we talk to them to pick something and take it out of draft mode once we accept it. We'll need language to explain this to people.
- exceptions for code licenses should have an extremely easy user experience. It's very common for someone to write code that uses other libraries, and this leads in to a need for flexibility with licensing. In my opinion we should also make it easy for people to share code from past projects -- and they may have already selected licenses for those, and the logistics for re-licensing could get tricky.

**Comment by victoriastodden** [comment]
Yes that's good - the canonical paper is here:
http://ijclp.net/old_website/article.php?doc=1&issue=13_2009 ;)

**Comment by codersquid** [comment]
;) I think for our static pages, that we could have a related page with explanations that link out to that paper as well as other papers that explain the user experience decisions we've made. This paper, the Gentleman and Temple-Lang paper, and papers that immediately relate to ResearchCompendia (for less immediately related literature, we could direct people to some of our other projects).

(except state that in a way unlike a programmer would state that, in other words, don't use "user experience decisions)

**Comment by victoriastodden** [comment]
It's a great idea. I will be happy to contribute to this.

**Comment by codersquid** [comment]
I have content picking CC0 by default, and an other if they want to take it up with us to pick something else. For src I have MIT by default, and other if they want to talk to us.

I haven't implemented any functionality to exclude pages where people have picked "other" from browsing and search, but maybe it is something we could do.
