### ISSUE TITLE
review browser card

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#61]
![screen shot 2013-11-12 at 12 01 34 pm](https://f.cloud.github.com/assets/529748/1524335/99351130-4bc4-11e3-971b-33ae6a62b847.png)

take a look at the browser card and rip it apart for me. Here my comments and questions.
- the title is an anchor link
  - that forces a color on our title.
  - I'd rather be able to click on the header to go to details
- the buttons
  - I don't know if those are the best words
  - I am uncertain about the icons on the buttons. the download icon is fairly widespread, but I don't know about using a book for going to details. It might be misleading for what happens (would they expect to browse a document, etc.)
- I agree about the color scheme needing to go away from the default blue
- Contents supplied by user
  - garbage in garbage out. There is no constraint on what the user can enter for journal, abstract, etc.

**Comment by codersquid** [comment]
Before I download things, I like to know what I am downloading. The buttons to links don't provide that. It should happen in a future enhancement, but for now, I am wondering if the buttons are a bad idea on the browse card, or I should take them off.

**Comment by jaseiler** [comment]
I like the way it looks now, words and icons.
I'm not sure how big a priority color is for now.
I'd rather have legible FAQs before we worry about icons or colors.  
Maybe in the future we can have hovering dropdowns for what download links to but it will usually be a zip or tarball of a lot of things, so that won't help much.

**Comment by codersquid** [comment]
> Maybe in the future we can have hovering dropdowns for what download links to but it will usually be a zip or tarball of a lot of things, so that won't help much. 

I was thinking that future users might write their abstracts similarly to the current ones, but when we encourage them with the help and tooltips, they might have a section with information a little more friendly about what the zips include.

and if that sounds like a good idea, we could increase the size limit for that fields, or perhaps have a new field, or etc. (decide impl details later).

**Comment by codersquid** [comment]
> I'd rather have legible FAQs before we worry about icons or colors.

I'm trying out the following for helping to visualize priorities: 
- _Backlog_ label means something is not ready to be worked on for our current two weeks.
-  _Ready_ label means that something is ready to be worked on for our current two weeks.
-  _In Progress_ identifies what I am working on immediately.

You can hit me with a clue-by-four if my _In Progress_ is something like hitting the site with a pretty stick versus working on the FAQ or something more important.

**Comment by codersquid** [comment]
I'm closing this, and any changes for the browser cards can be tracked in new issues.
