### ISSUE TITLE
frontend url design

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#62]
Frontend as somewhat distinct from #10.

Up until now I've used my best judgement for url designs along with some hacky things based on my intermediate knowledge of django.
- `/slug` for static pages, where `slug` is a human readable url appropriate string such as [about](http://researchcompendia.org/about/)
- `/compendia/` for [browsing](http://researchcompendia.org/compendia/) compendia. more generally, I like `/pluralnoun/` for browsing and for going to an id
- `/compendia/pk`, where pk is the id of the compendium.
- `/users/pk`, where pk is the id of the [user](http://researchcompendia.org/users/1/)
- `/compendia/create` to create compendia
- `/compendia/update/pk` to update compendia pk

Rather than pk, it could be better to use a hash. such as done by the [idgen](https://pypi.python.org/pypi/idgen). There are reasons why you might not want to expose pk's, we can decide.

I have having `create` and `update` in my url and wonder what is common practice in django. In my old jobs I never had to worry about front end urls like this, I did everything on the backend and could use POST, PUT, etc. rather than have verbs in the url like that.

For search, I am expecting to use params and perhaps some path segments where it makes sense to. in other words, `/compendia/?create_date=foo` and so on to return compendia that match the params. I have not decided whether we should use path segments, I think that is premature for us to do, since picking a path segment is a huge decision. We used some path segments for some of the search queries at my old job and I could discuss reasons later.

**Comment by codersquid** [comment]
Please share review comments.

**Comment by codersquid** [comment]
also, I note that github uses `/user/repo/issues/new` so maybe I'm not completely crazy for putting verbs in my url.

**Comment by jaseiler** [comment]
The url design is fine, but I didn't know where to put these comments:
1) I would rather be directed back to the main page after logging in, than to my account info.  I don't need to see myself every time I login. Though the might be different if I had a list of compendia. Maybe only link back to the user's account page upon signing in if they already have existing compendia.

2) There needs to be a create page link on the top or bottom bar. It should always be accessible.
