### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#81]

**Comment by jaseiler** [comment]
I put it in the base.html template, and it seems to be working.  I'm getting live updates in my chrome analytics plugin.

**Comment by codersquid** [comment]
That sounds good to push.

**Comment by codersquid** [comment]
Do you want to merge your change?

**Comment by codersquid** [comment]
Nevermind, I see you did. https://github.com/researchcompendia/tyler/commit/40699b25bf2df19b8eef8f8eb500228afed30ccd

For making changes, I've started doing pull requests and I try to remember to add a reference to the related issue in the comment so that the commit is linked to the issue and shows up in notifications. Let's all do that.
