### ISSUE TITLE
get official Academic Commons logo from Columbia

### ISSUE THREAD

**Issue by codersquid** [researchcompendia/researchcompendia#98]
I'm waiting on the logo from the Columbia logo contact email address.

(I'm opening this issue so that we don't let this escape)

**Comment by victoriastodden** [comment]
I'm not sure I can get it - the original person I knew there seems to have
moved on. We can leave this ticket open though and I will see what I can do.

Victoria

**Comment by codersquid** [comment]
I emailed the address on the [logo](http://www.columbia.edu/content/logo.html) page but sent the email over the holiday. Maybe I'll get a reply later this week.

**Comment by victoriastodden** [comment]
Let me work on this one.

Victoria
